export const SET_CURRENT_IMAGE = "SET_CURRENT_IMAGE";
export const START_FETCHING_CURRENT_IMAGE = "START_FETCHING_CURRENT_IMAGE";
export const SET_FAVORITES = "SET_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const START_FETCHING_FAVORITES = "START_FETCHING_FAVORITES";
export const START_REMOVING_FROM_FAVORITES = "START_REMOVING_FROM_FAVORITES";
export const START_LIKING_IMAGE = "START_LIKING_IMAGE";
export const ADD_IMAGE_TO_FAVORITES = "ADD_IMAGE_TO_FAVORITES";
